#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kim-api
Version  : 2.l.3
Release  : 6
URL      : https://github.com/openkim/kim-api/archive/v2.1.3/kim-api-2.l.3.tar.gz
Source0  : https://github.com/openkim/kim-api/archive/v2.1.3/kim-api-2.l.3.tar.gz
Summary  : The Open Knowledgebase of Interatomic Models (OpenKIM)
Group    : Development/Tools
License  : CDDL-1.0
Requires: kim-api-bin = %{version}-%{release}
Requires: kim-api-data = %{version}-%{release}
Requires: kim-api-lib = %{version}-%{release}
Requires: kim-api-libexec = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : git
BuildRequires : vim

%description
The KIM API package is a system-level library that aims to give computer
programmers the ability to write atomistic or molecular simulation programs
that can seamlessly interface with implementations of interatomic models,
regardless of the programming language (C, C++, Fortran, Python, etc.)
in which the codes are written.
It is part of the larger KIM project (https://openkim.org).

%package bin
Summary: bin components for the kim-api package.
Group: Binaries
Requires: kim-api-data = %{version}-%{release}
Requires: kim-api-libexec = %{version}-%{release}

%description bin
bin components for the kim-api package.


%package data
Summary: data components for the kim-api package.
Group: Data

%description data
data components for the kim-api package.


%package dev
Summary: dev components for the kim-api package.
Group: Development
Requires: kim-api-lib = %{version}-%{release}
Requires: kim-api-bin = %{version}-%{release}
Requires: kim-api-data = %{version}-%{release}
Provides: kim-api-devel = %{version}-%{release}
Requires: kim-api = %{version}-%{release}

%description dev
dev components for the kim-api package.


%package extras
Summary: extras components for the kim-api package.
Group: Default

%description extras
extras components for the kim-api package.


%package lib
Summary: lib components for the kim-api package.
Group: Libraries
Requires: kim-api-data = %{version}-%{release}
Requires: kim-api-libexec = %{version}-%{release}

%description lib
lib components for the kim-api package.


%package libexec
Summary: libexec components for the kim-api package.
Group: Default

%description libexec
libexec components for the kim-api package.


%prep
%setup -q -n kim-api-2.1.3
cd %{_builddir}/kim-api-2.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573318022
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DBASH_COMPLETION_COMPLETIONSDIR=/usr/share/bash-completion/completions \
-DZSH_COMPLETION_COMPLETIONSDIR=/usr/share/zsh/functions/Completion/Unix
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1573318022
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kim-api-collections-management

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/kim-api-collections-management.bash
/usr/share/cmake/*
/usr/share/emacs/site-lisp/kim-api/kim-api-c-style.el
/usr/share/zsh/functions/Completion/Unix/_kim-api-collections-management
/usr/share/zsh/functions/Completion/Unix/kim-api-collections-management.bash

%files dev
%defattr(-,root,root,-)
/usr/include/kim-api/KIM_ChargeUnit.h
/usr/include/kim-api/KIM_ChargeUnit.hpp
/usr/include/kim-api/KIM_Collection.h
/usr/include/kim-api/KIM_Collection.hpp
/usr/include/kim-api/KIM_CollectionItemType.h
/usr/include/kim-api/KIM_CollectionItemType.hpp
/usr/include/kim-api/KIM_Collections.h
/usr/include/kim-api/KIM_Collections.hpp
/usr/include/kim-api/KIM_ComputeArgumentName.h
/usr/include/kim-api/KIM_ComputeArgumentName.hpp
/usr/include/kim-api/KIM_ComputeArguments.h
/usr/include/kim-api/KIM_ComputeArguments.hpp
/usr/include/kim-api/KIM_ComputeCallbackName.h
/usr/include/kim-api/KIM_ComputeCallbackName.hpp
/usr/include/kim-api/KIM_DataType.h
/usr/include/kim-api/KIM_DataType.hpp
/usr/include/kim-api/KIM_EnergyUnit.h
/usr/include/kim-api/KIM_EnergyUnit.hpp
/usr/include/kim-api/KIM_FunctionTypes.h
/usr/include/kim-api/KIM_FunctionTypes.hpp
/usr/include/kim-api/KIM_LOG_DEFINES.inc
/usr/include/kim-api/KIM_LanguageName.h
/usr/include/kim-api/KIM_LanguageName.hpp
/usr/include/kim-api/KIM_LengthUnit.h
/usr/include/kim-api/KIM_LengthUnit.hpp
/usr/include/kim-api/KIM_Log.h
/usr/include/kim-api/KIM_Log.hpp
/usr/include/kim-api/KIM_LogMacros.h
/usr/include/kim-api/KIM_LogMacros.hpp
/usr/include/kim-api/KIM_LogVerbosity.h
/usr/include/kim-api/KIM_LogVerbosity.hpp
/usr/include/kim-api/KIM_Model.h
/usr/include/kim-api/KIM_Model.hpp
/usr/include/kim-api/KIM_ModelCompute.h
/usr/include/kim-api/KIM_ModelCompute.hpp
/usr/include/kim-api/KIM_ModelComputeArguments.h
/usr/include/kim-api/KIM_ModelComputeArguments.hpp
/usr/include/kim-api/KIM_ModelComputeArgumentsCreate.h
/usr/include/kim-api/KIM_ModelComputeArgumentsCreate.hpp
/usr/include/kim-api/KIM_ModelComputeArgumentsDestroy.h
/usr/include/kim-api/KIM_ModelComputeArgumentsDestroy.hpp
/usr/include/kim-api/KIM_ModelCreate.h
/usr/include/kim-api/KIM_ModelCreate.hpp
/usr/include/kim-api/KIM_ModelDestroy.h
/usr/include/kim-api/KIM_ModelDestroy.hpp
/usr/include/kim-api/KIM_ModelDriverCreate.h
/usr/include/kim-api/KIM_ModelDriverCreate.hpp
/usr/include/kim-api/KIM_ModelDriverHeaders.h
/usr/include/kim-api/KIM_ModelDriverHeaders.hpp
/usr/include/kim-api/KIM_ModelExtension.h
/usr/include/kim-api/KIM_ModelExtension.hpp
/usr/include/kim-api/KIM_ModelHeaders.h
/usr/include/kim-api/KIM_ModelHeaders.hpp
/usr/include/kim-api/KIM_ModelRefresh.h
/usr/include/kim-api/KIM_ModelRefresh.hpp
/usr/include/kim-api/KIM_ModelRoutineName.h
/usr/include/kim-api/KIM_ModelRoutineName.hpp
/usr/include/kim-api/KIM_ModelWriteParameterizedModel.h
/usr/include/kim-api/KIM_ModelWriteParameterizedModel.hpp
/usr/include/kim-api/KIM_Numbering.h
/usr/include/kim-api/KIM_Numbering.hpp
/usr/include/kim-api/KIM_SemVer.h
/usr/include/kim-api/KIM_SemVer.hpp
/usr/include/kim-api/KIM_SimulatorHeaders.h
/usr/include/kim-api/KIM_SimulatorHeaders.hpp
/usr/include/kim-api/KIM_SimulatorModel.h
/usr/include/kim-api/KIM_SimulatorModel.hpp
/usr/include/kim-api/KIM_SpeciesName.h
/usr/include/kim-api/KIM_SpeciesName.hpp
/usr/include/kim-api/KIM_SupportStatus.h
/usr/include/kim-api/KIM_SupportStatus.hpp
/usr/include/kim-api/KIM_SupportedExtensions.h
/usr/include/kim-api/KIM_SupportedExtensions.hpp
/usr/include/kim-api/KIM_TemperatureUnit.h
/usr/include/kim-api/KIM_TemperatureUnit.hpp
/usr/include/kim-api/KIM_TimeUnit.h
/usr/include/kim-api/KIM_TimeUnit.hpp
/usr/include/kim-api/KIM_UnitSystem.h
/usr/include/kim-api/KIM_UnitSystem.hpp
/usr/include/kim-api/KIM_Version.h
/usr/include/kim-api/KIM_Version.hpp
/usr/lib64/kim-api/cmake/KIM_SharedLibrarySchema.hpp
/usr/lib64/kim-api/cmake/item-compiled-with-version.txt.in
/usr/lib64/kim-api/cmake/item-info.txt.in
/usr/lib64/kim-api/cmake/item-wrapper.cpp.in
/usr/lib64/kim-api/mod/kim_charge_unit_module.mod
/usr/lib64/kim-api/mod/kim_collection_item_type_module.mod
/usr/lib64/kim-api/mod/kim_collection_module.mod
/usr/lib64/kim-api/mod/kim_collections_module.mod
/usr/lib64/kim-api/mod/kim_compute_argument_name_module.mod
/usr/lib64/kim-api/mod/kim_compute_arguments_module.mod
/usr/lib64/kim-api/mod/kim_compute_callback_name_module.mod
/usr/lib64/kim-api/mod/kim_data_type_module.mod
/usr/lib64/kim-api/mod/kim_energy_unit_module.mod
/usr/lib64/kim-api/mod/kim_language_name_module.mod
/usr/lib64/kim-api/mod/kim_length_unit_module.mod
/usr/lib64/kim-api/mod/kim_log_module.mod
/usr/lib64/kim-api/mod/kim_log_verbosity_module.mod
/usr/lib64/kim-api/mod/kim_model_compute_arguments_create_module.mod
/usr/lib64/kim-api/mod/kim_model_compute_arguments_destroy_module.mod
/usr/lib64/kim-api/mod/kim_model_compute_arguments_module.mod
/usr/lib64/kim-api/mod/kim_model_compute_module.mod
/usr/lib64/kim-api/mod/kim_model_create_module.mod
/usr/lib64/kim-api/mod/kim_model_destroy_module.mod
/usr/lib64/kim-api/mod/kim_model_driver_create_module.mod
/usr/lib64/kim-api/mod/kim_model_driver_headers_module.mod
/usr/lib64/kim-api/mod/kim_model_extension_module.mod
/usr/lib64/kim-api/mod/kim_model_headers_module.mod
/usr/lib64/kim-api/mod/kim_model_module.mod
/usr/lib64/kim-api/mod/kim_model_refresh_module.mod
/usr/lib64/kim-api/mod/kim_model_routine_name_module.mod
/usr/lib64/kim-api/mod/kim_model_write_parameterized_model_module.mod
/usr/lib64/kim-api/mod/kim_numbering_module.mod
/usr/lib64/kim-api/mod/kim_sem_ver_module.mod
/usr/lib64/kim-api/mod/kim_simulator_headers_module.mod
/usr/lib64/kim-api/mod/kim_simulator_model_module.mod
/usr/lib64/kim-api/mod/kim_species_name_module.mod
/usr/lib64/kim-api/mod/kim_support_status_module.mod
/usr/lib64/kim-api/mod/kim_supported_extensions_module.mod
/usr/lib64/kim-api/mod/kim_temperature_unit_module.mod
/usr/lib64/kim-api/mod/kim_time_unit_module.mod
/usr/lib64/kim-api/mod/kim_unit_system_module.mod
/usr/lib64/libkim-api.so
/usr/lib64/pkgconfig/libkim-api.pc

%files extras
%defattr(-,root,root,-)
/usr/lib64/kim-api/model-drivers/LennardJones612__MD_414112407348_003/libkim-api-model-driver.so
/usr/lib64/kim-api/model-drivers/ex_model_driver_P_LJ/libkim-api-model-driver.so
/usr/lib64/kim-api/model-drivers/ex_model_driver_P_Morse/libkim-api-model-driver.so
/usr/lib64/kim-api/portable-models/LennardJones612_UniversalShifted__MO_959249795837_003/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/LennardJones_Ar/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_LJ/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_MLJ_Fortran/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_Morse/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_Morse_07C/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_Morse_07C_w_Extensions/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_P_Morse_MultiCutoff/libkim-api-portable-model.so
/usr/lib64/kim-api/portable-models/ex_model_Ar_SLJ_MultiCutoff/libkim-api-portable-model.so
/usr/lib64/kim-api/simulator-models/Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu/libkim-api-simulator-model.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkim-api.so.2

%files libexec
%defattr(-,root,root,-)
/usr/libexec/kim-api/kim-api-collections-info
/usr/libexec/kim-api/kim-api-shared-library-test
/usr/libexec/kim-api/kim-api-simulator-model
